# <- processor ->

# Override the minimum age before a scan request is sent to the target (Default 10m):
minimum-age: 0m

# Override the delay between processed scans (Default 5s):
scan-delay: 5s

# override the interval scan stats are displayed (defaults to 1 hour / 0s to disable):
scan-stats: 1h

# Set anchor files for remote storage. If these are missing no scans will be sent to the target to avoid files being trashed when a mount fails
anchors:
  - /mnt/user/data/realdebrid/version.txt

# <- triggers ->

# Port for Autoscan webhooks to listen on
port: 3030

triggers:
  # The manual trigger is always enabled, the config only adjusts its priority and the rewrite rules.
  manual:
    priority: 5
    rewrite:
      - from: /mnt/user/data/
        to: /mnt/user/data/

  inotify:
    - priority: 10
      paths:
        - path: /mnt/user/data/riven_library/movies
        - path: /mnt/user/data/riven_library/shows
      # filter with regular expressions
      include:
        - ^/mnt/user/data/riven_library/
      exclude:
        - '\.(srt|pdf)$'
      # rewrite inotify path to unified filesystem
      rewrite:
            - from: /mnt/user/data/riven_library/
              to: /mnt/user/data/riven_library/

  radarr:
    - name: radarr   # /triggers/radarr
      priority: 0
    - name: radarr4k # /triggers/radarr4k
      priority: 0
  sonarr:
    - name: sonarr # /triggers/sonarr
      priority: 5
    - name: sonarr4k # /triggers/sonarr4k
      priority: 5
      

targets:
  plex:
    - url: "http://192.168.1.1:32400/"
      token: PfrYqCzsz45wihMRrg2z
      rewrite:
        - from: /mnt/user/data/
          to: /mnt/user/data/